# Generated by Django 5.0.6 on 2024-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='alert',
            name='destination_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
