# Generated by Django 5.0.6 on 2024-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_rename_comments_incident_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='name',
        ),
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
