name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: core.settings  # Adjust if your settings module is different
      run: |
        python manage.py test
    
    - name: Generate key for password manager
      run: |
        mkdir -p password_manager
        python -c "from cryptography.fernet import Fernet; key = Fernet.generate_key(); with open('password_manager/key.key', 'wb') as key_file: key_file.write(key)"

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
    
    - name: Migrate database
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: core.settings  # Adjust if your settings module is different
      run: |
        python manage.py migrate

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'olivia-le'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
