name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate key if not exists
      run: |
        source antenv/bin/activate
        echo "import os
from cryptography.fernet import Fernet

key_path = 'password_manager/key.key'

def generate_key():
    key = Fernet.generate_key()
    with open(key_path, 'wb') as key_file:
        key_file.write(key)

if not os.path.exists(key_path):
    generate_key()
" > generate_key.py
        python generate_key.py

    - name: Run migrations
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        source antenv/bin/activate
        python manage.py migrate

    - name: Collect static files
      run: |
        source antenv/bin/activate
        python manage.py collectstatic --noinput

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'olivia-le'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
