name: Olivia LE CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate key if missing
      run: |
        python generate_key.py

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Cache static files
      id: cache-static
      uses: actions/cache@v2
      with:
        path: |
          staticfiles
        key: ${{ runner.os }}-static-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/static/**/*') }}
        restore-keys: |
          ${{ runner.os }}-static-

    - name: Collect static files
      if: steps.cache-static.outputs.cache-hit != 'true'
      run: |
        python manage.py collectstatic --noinput

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'olivia-le'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
